#config for cloud run
steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/southern-engine-405812/strapi-sandbox", "."]

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/southern-engine-405812/strapi-sandbox"]

options:
  logging: CLOUD_LOGGING_ONLY